services:
  - type: web
    name: 3play
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: https://3play.cz,https://www.3play.cz
        sync: false
      - key: APP_ORIGIN
        value: https://3play.cz
        sync: false
      - key: API_ORIGIN
        value: https://3play.cz
        sync: false
