export const countries = [
  { code: 'CZ', name: 'Česká republika', dial: '+420', flag: '🇨🇿' },
  { code: 'SK', name: 'Slovensko', dial: '+421', flag: '🇸🇰' },
  { code: 'US', name: 'Spojené státy', dial: '+1', flag: '🇺🇸' },
  { code: 'GB', name: 'Velká Británie', dial: '+44', flag: '🇬🇧' },
  { code: 'DE', name: 'Německo', dial: '+49', flag: '🇩🇪' },
  { code: 'PL', name: 'Polsko', dial: '+48', flag: '🇵🇱' },
  { code: 'AT', name: 'Rakousko', dial: '+43', flag: '🇦🇹' },
  { code: 'FR', name: 'Francie', dial: '+33', flag: '🇫🇷' },
  { code: 'IT', name: 'Itálie', dial: '+39', flag: '🇮🇹' },
  { code: 'ES', name: 'Španělsko', dial: '+34', flag: '🇪🇸' },
  { code: 'UA', name: 'Ukrajina', dial: '+380', flag: '🇺🇦' },
  { code: 'VN', name: 'Vietnam', dial: '+84', flag: '🇻🇳' },
  { code: 'RU', name: 'Rusko', dial: '+7', flag: '🇷🇺' },
  { code: 'HU', name: 'Maďarsko', dial: '+36', flag: '🇭🇺' },
  { code: 'RO', name: 'Rumunsko', dial: '+40', flag: '🇷🇴' },
  { code: 'BG', name: 'Bulharsko', dial: '+359', flag: '🇧🇬' },
  { code: 'HR', name: 'Chorvatsko', dial: '+385', flag: '🇭🇷' },
  { code: 'RS', name: 'Srbsko', dial: '+381', flag: '🇷🇸' },
  { code: 'GR', name: 'Řecko', dial: '+30', flag: '🇬🇷' },
  { code: 'TR', name: 'Turecko', dial: '+90', flag: '🇹🇷' },
  { code: 'CN', name: 'Čína', dial: '+86', flag: '🇨🇳' },
  { code: 'JP', name: 'Japonsko', dial: '+81', flag: '🇯🇵' },
  { code: 'KR', name: 'Jižní Korea', dial: '+82', flag: '🇰🇷' },
  { code: 'IN', name: 'Indie', dial: '+91', flag: '🇮🇳' },
  { code: 'BR', name: 'Brazílie', dial: '+55', flag: '🇧🇷' },
  { code: 'CA', name: 'Kanada', dial: '+1', flag: '🇨🇦' },
  { code: 'AU', name: 'Austrálie', dial: '+61', flag: '🇦🇺' },
] as const
